name: Creates a docker image for production

on:
  push:
    tags:
      - "v*"

jobs:
  build_docker:
    name: Build the docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: redbeard/dev-tunnel
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          no-cache: true
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs:
      - build_docker
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Curl -XPOST URL
        run: curl -XPOST https://portainer.makecodes.dev/api/webhooks/c9edd686-4c24-434f-9670-92e51ac5b801
